DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	USERNAME VARCHAR(50) UNIQUE          NOT NULL,
	PASSWORD VARCHAR(40)                 NOT NULL,
	BALANCE DECIMAL(14,2) DEFAULT 0.0    NOT NULL
);

DROP TABLE IF EXISTS log;
CREATE TABLE IF NOT EXISTS log(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	USERNAME VARCHAR(50) 				 NOT NULL,
	TIME	 INTEGER                     NOT NULL,
	OPERATOR VARCHAR(20)                 NOT NULL,
	MONEY    DECIMAL(14,2) DEFAULT 0.0   NOT NULL
);
