DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user(
<<<<<<< HEAD
	ID INTEGER PRIMARY KEY AUTOINCREMENT        NOT NULL,
	USERNAME VARCHAR(100) UNIQUE                NOT NULL,
	PASSWORD VARCHAR(100)                       NOT NULL,
	BALANCE DECIMAL(14,2) DEFAULT 0.0           NOT NULL
=======
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	USERNAME VARCHAR(50) UNIQUE          NOT NULL,
	PASSWORD VARCHAR(40)                 NOT NULL,
	BALANCE DECIMAL(14,2) DEFAULT 0.0    NOT NULL
>>>>>>> e69753ce7b3dbb6255efedcc917a50ad053876ce
);

DROP TABLE IF EXISTS log;
CREATE TABLE IF NOT EXISTS log(
<<<<<<< HEAD
	ID INTEGER PRIMARY KEY AUTOINCREMENT        NOT NULL,
	USERNAME VARCHAR(100) 		                NOT NULL,
	TIME	 INTEGER  DEFAULT CURRENT_TIMESTAMP NOT NULL,
	OPERATOR VARCHAR(200)                       NOT NULL,
	MONEY    DECIMAL(14,2) DEFAULT 0.0          NOT NULL
=======
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	USERNAME VARCHAR(50) 				 NOT NULL,
	TIME	 INTEGER                     NOT NULL,
	OPERATOR VARCHAR(20)                 NOT NULL,
	MONEY    DECIMAL(14,2) DEFAULT 0.0   NOT NULL
>>>>>>> e69753ce7b3dbb6255efedcc917a50ad053876ce
);
