DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user(
	ID INTEGER PRIMARY KEY AUTOINCREMENT        NOT NULL,
	USERNAME VARCHAR(100) UNIQUE                NOT NULL,
	PASSWORD VARCHAR(100)                       NOT NULL,
	BALANCE DECIMAL(14,2) DEFAULT 0.0           NOT NULL
);

DROP TABLE IF EXISTS log;
CREATE TABLE IF NOT EXISTS log(
	ID INTEGER PRIMARY KEY AUTOINCREMENT        NOT NULL,
	USERNAME VARCHAR(100) 		                NOT NULL,
	TIME	 INTEGER  DEFAULT CURRENT_TIMESTAMP NOT NULL,
	OPERATOR VARCHAR(200)                       NOT NULL,
	MONEY    DECIMAL(14,2) DEFAULT 0.0          NOT NULL
);
